### ISSUE TITLE
Your code is on a deadmu5 album cover!

### ISSUE THREAD

**Issue by SM-G950U** [sweetsoftware/FTPKeyLogger#1]
Hello there, there is no problem with your keylogger, but I wanted to let you know some people have found the start of this keylogger was on the album cover to [SATRN](https://www.youtube.com/watch?v=ggWVLilQNkw) by deadmau5. Have fun knowing that fact, and that there are probably few out there that will ever find this.  Just tell me when you see this and I'll close it, this just seemed like the best way of telling you.

**Comment by sweetsoftware** [comment]
Hey there, that's cool ! how did you find about that ?

**Comment by SM-G950U** [comment]
The song was released Friday, and people in the comments were saying it looks like real code of some kind. One guy had just posted a link here when I left that. I think very few know.

**Comment by krakatorange** [comment]
Yep. He basically led us all here.

**Comment by SM-G950U** [comment]
Today his next song "Coasted" released, they have the same cover with the colors changed, so you made it on there too!
